### ISSUE TITLE
How to set up scenes configuration

### ISSUE THREAD

**Issue by danydhondt** [hoaiduyit/react-pannellum#15]
Could. you please provide a tour example? How to setup scenes?

Thanks in advance

**Comment by danydhondt** [comment]
Found it out myself by analyzing the source code.
Great job! Thanks!

**Comment by hoaiduyit** [comment]
Hi @danydhondt ,
Nice to see you can find the solution by yourself.

**Comment by philsinatra** [comment]
@danydhondt Could you point out where you referenced to build out an example for anyone trying to get up and running quickly?
