### ISSUE TITLE
The file could not be accessed BUG.

### ISSUE THREAD

**Issue by isaacp0310** [hoaiduyit/react-pannellum#22]
Hi, first of all
When i'm trying to load the image with this component, in a AWS S3 Bucket, it shows me the following error:

![img1](https://user-images.githubusercontent.com/35440957/79343603-92ebb280-7efc-11ea-8b43-167a16d4e231.png)

**This is the link of the image: to show that it works nicely**
https://otekdo-asset-store.s3.amazonaws.com/dealers/quiri-assets/360/a1-80.jpg

The console says this:

![image](https://user-images.githubusercontent.com/35440957/79343748-cdede600-7efc-11ea-98e5-bd967d7c77cf.png)

**But i'm pretty sure that i had setup CORS in my S3 Bucket**
This is my CORS SETUP in my S3 bucket

`<?xml version="1.0" encoding="UTF-8"?>
<CORSConfiguration xmlns="http://s3.amazonaws.com/doc/2006-03-01/">
<CORSRule>
    <AllowedOrigin>*</AllowedOrigin>
    <AllowedMethod>GET</AllowedMethod>
    <AllowedMethod>HEAD</AllowedMethod>
    <MaxAgeSeconds>3000</MaxAgeSeconds>
    <AllowedHeader>*</AllowedHeader>
</CORSRule>
</CORSConfiguration>
`

**But the problem that it's more weird, it that react-pannelum works perfectly with  Mozilla Firefox, and the same image URL.** 

**Firefox**
![image](https://user-images.githubusercontent.com/35440957/79344055-4785d400-7efd-11ea-8a3c-ebe1d1b0bba1.png)

**Chrome**
![image](https://user-images.githubusercontent.com/35440957/79344497-eca0ac80-7efd-11ea-8910-fdb5bd5052b6.png)

**Opera**
![image](https://user-images.githubusercontent.com/35440957/79344609-0d690200-7efe-11ea-8690-c4d5f55b2f08.png)

**React Pannelum compatibility with different browsers:**

**NEWS
After clearing the cache again, the (Image with React Panellum )now does not get rendered in any browsers**

*Firefox: Do not Work
*Opera: Do not Work
*Opera gaming edition: Do not Work
*Google Chrome: Do not Work
*Microsoft Edge (With chromiun engine): Do not Work

*I already cleaned cache a couple of times
*I already tried to setup CORS multiple times, but it still does not work
*Firefox works even not beign on incognito mode, the other browsers has the problem

Amazing component by the way!

**Comment by tforsbacka** [comment]
Hi,
Are you sure that this is related to the component?
Have you tried to load the image in a html img tag?

**Comment by isaacp0310** [comment]
Hi, yeah!
Of course that's why i also provided the url Link

**This is the link of the image: to show that it works nicely**
https://otekdo-asset-store.s3.amazonaws.com/dealers/quiri-assets/360/a1-80.jpg

**Comment by tforsbacka** [comment]
Hi,
Just to be clear here. You can render the image with the component outside you production environment? You can render the image in an img tag in your production environment?
How can this issue be reproduced?

**Comment by isaacp0310** [comment]
**NEWS**
**After clearing the cache again, the (Image with React Panellum )now does not get rendered in any browsers**

The Component does not render in production environment and also does not render on development environment.
I'm gonna show you this example 

**This is google Chrome**
![image](https://user-images.githubusercontent.com/35440957/79480614-54c5c000-7fdc-11ea-926a-e8047b683110.png)

**This is Mozilla Firefox**
![image](https://user-images.githubusercontent.com/35440957/79481071-0238d380-7fdd-11ea-8542-fc6178eb9679.png)

**This is google chrome in the production mode**
![image](https://user-images.githubusercontent.com/35440957/79481411-75424a00-7fdd-11ea-9e9e-947a99b38d75.png)

**This is Firefox in the production mode**
![image](https://user-images.githubusercontent.com/35440957/79481521-9d31ad80-7fdd-11ea-9dc0-b583f8590b0e.png)

**And that bug still persists in the other browsers as i explained before.**

**Comment by tforsbacka** [comment]
Hi,
I’m not able to reproduce the issue. Your image is rendering fine for me with the component in my dev env.

**Comment by isaacp0310** [comment]
Wow, it is so weird, well i'm gonna clean the cache again with ccleaner.

**Comment by tforsbacka** [comment]
Hi,
I'm using the latest version of the component. I find it very unlikely that you issue is related to this component. It's however easy to find out. On your react page. Render your image in this component **and** in an img tag. Will it be rendered in your img tag but not in the component?

**Comment by isaacp0310** [comment]
**Well, now akwardly it works well without any error (When i always clean the cache), but i think i'll wait for this component to get some updates (In case of some problems comes along the way)**
@tforsbacka , A lot of thanks for also testing and asking,
And @hoaiduyit , amazing component btw!

**Comment by hoaiduyit** [comment]
Hi @isaacp0310 ,
No problem, just report error if you find any
Thank for using my component.

**Comment by butterfly-coder** [comment]
Hi @isaacp0310 
I've faced same problem and solved it!
Perhaps this will be helpful. 
https://github.com/mpetroff/pannellum/issues/148#issuecomment-494258212
Good luck!!!

**Comment by isaacp0310** [comment]
Wow!, @butterfly-coder  congratulations, 
but which solution did you use exactly?
i mean they're talking about solutions with lambda and other stuff
i would love to know what you have done exactly with react or other stuff

**Comment by butterfly-coder** [comment]
@isaacp0310 
Please check as follow: 
1. Check if you set aws s3 cors configuration correctly
2. Check if you use the image url as src attribute in img tag

**Comment by isaacp0310** [comment]
@butterfly-coder Wow, it works!
I set up properly the query pararameter only in the HTML code

While with javascript i fetch the image with another method

**Example:**

**In the html it looks like this (In the react pannelum component , JSX)**
`<img  src="myImage.png?x-request=html" />`

**While with javascript i fetched the image prior rendering**
`let imageToFetch=new Image();`
`imageToFetch.src = 'myImage.png';`

**And i was testing it more than 20 times, and it works nicely!, it does not show that error anymore**
