### ISSUE TITLE
startAutoRotate() function doesn't work : ReferenceError: pitch is not defined

### ISSUE THREAD

**Issue by butterfly-coder** [hoaiduyit/react-pannellum#26]
When I call startAutoRotate function, I've got an error like follow : 
ReferenceError: pitch is not defined
startAutoRotate
.../node_modules/react-pannellum/dist/index.es.js:4907
  4904 | key: "startAutoRotate",
  4905 | value: function startAutoRotate(speed) {
  4906 |   constants.myPromise(myPannellum, {
> 4907 |     pitch: pitch
       | ^  4908 |   }).then(function (_ref6) {
  4909 |     var pitch = _ref6.pitch;
  4910 |     myPannellum.startAutoRotate(speed);

**Comment by hoaiduyit** [comment]
Hi @butterfly-coder , 

I just update my newest code to this. Please install new version `0.1.12` to get this fix. 
I added 01 parameter for this function. Now you have to use with `startAutoRotate(speed, pitch)`.
Note: if you have any question, just ask me.

Thanks.

**Comment by butterfly-coder** [comment]
Thanks for your update. it works well.
😁
