### ISSUE TITLE
How to take screenshot from current view

### ISSUE THREAD

**Issue by crauf** [hoaiduyit/react-pannellum#29]
Hi, I'd like to take screenshot from current view.
Does it support screenshot?
I can see this feature from pannellum library but I can't sure if this module supports it.

**Comment by hoaiduyit** [comment]
Hi @butterfly-coder , 
I will find out how to implement this.
Regards,

**Comment by butterfly-coder** [comment]
Thanks so much. @hoaiduyit

**Comment by hoaiduyit** [comment]
Hi @butterfly-coder , sorry, I dont think the library is support screenshot at the moment.
