### ISSUE TITLE
Config props 'previewImage ' It doesn't work

### ISSUE THREAD

**Issue by MrSandManSy** [hoaiduyit/react-pannellum#3]
Thank you for your code.There is a problem,Config props 'previewImage ', it doesn't work.
![image](https://user-images.githubusercontent.com/28557698/48749535-60fa0080-ecb6-11e8-9747-5d07718ed6c5.png)

![image](https://user-images.githubusercontent.com/28557698/48764875-d8965280-eceb-11e8-82c5-b2a045cb9a57.png)

**Comment by hoaiduyit** [comment]
@MrSandManSy , I'm sorry for the lately reply, I will check it again and tell you what happened.

**Comment by sutrixduych** [comment]
Hi @MrSandManSy , I know your problem. You should leave the `previewImage` in the `config` just like this.
```js
config = {
  previewImage: 'your image'
}
``` 
and it'll work like charm. Please read the docs more carefully. Thank you.

**Comment by hoaiduyit** [comment]
Hi @MrSandManSy , I know your problem. You should leave the `previewImage` in the `config` just like this.
```js
config = {
  previewImage: 'your image'
}
```
and it'll work like charm. Please read the docs more carefully. Thank you.
