### ISSUE TITLE
How to make fade effect when navigating between scenes

### ISSUE THREAD

**Issue by butterfly-coder** [hoaiduyit/react-pannellum#33]
Hi, I'm trying now to make fade effect when navigating between scenes.
Anybody solved this problem?

**Comment by hoaiduyit** [comment]
Hi @butterfly-coder ,

I will take a look and see what can I do.

Regards,

**Comment by butterfly-coder** [comment]
Thanks so much. @hoaiduyit 
This component is great.

**Comment by Couiljer** [comment]
Hi there, 
First thanks for this package ! 

I don't know if I misread documentation, but I can't find how to create a tour with scenes links. Is there a way to configure all scenes from the start ? Could you add a tour example ? 

The only info I found in the doc are : "_A tour configuration file is required for scene hot spots._"

**Comment by hoaiduyit** [comment]
Hi @Couiljer, @butterfly-coder  you can use `addScene` to add new scene, then use `addHotSpot` to link from current scene to new scene that you just created. Hope this can help.

**Comment by butterfly-coder** [comment]
Hi, @hoaiduyit 
Thanks for your help. But what I want to know is how to make fade effect when navigating between scenes.
Already I have a tour using `addScene` and `addHotspot`.
