### ISSUE TITLE
Expose .destroy() function from pannellum

### ISSUE THREAD

**Issue by rj-david** [hoaiduyit/react-pannellum#34]
@hoaiduyit Thanks for this.

Is it possible to expose the .destroy() function from pannellum? This helps to prevent memory leaks

**Comment by hoaiduyit** [comment]
Hi @rj-david ,

I will export this function to use as an import.

Regards,

**Comment by rj-david** [comment]
Thanks @hoaiduyit

**Comment by hoaiduyit** [comment]
Hi @rj-david ,

`destroy` function has been exposed and you can use like another functions.

Regards,
