### ISSUE TITLE
Remove tooltip with link to https://pannellum.org/ when right clicking

### ISSUE THREAD

**Issue by schystz** [hoaiduyit/react-pannellum#38]
Is it possible to remove the tooltip with link to https://pannellum.org/ when right clicking?

![image](https://i.imgur.com/k63fQnw.png)

**Comment by Marty-McFlyer** [comment]
Love the API but it doesn't seem to eliminate the default behavior with either of these calls:
   viewer.off('contextmenu',null);
   viewer.on('contextmenu',function(e) {
						e.preventDefault(); // useless, doesn't disable default menu
                     });

I was able to add an event listener to the parent div for contextmenu events but I'm left with the default menu still appearing.

**Comment by hoaiduyit** [comment]
Hi @schystz , @Marty-McFlyer ,

I will what I can do about this.

Thanks.

**Comment by ahoess** [comment]
Hi @schystz , @Marty-McFlyer 

Was actually just working on this ..

CSS should do the trick - event is still there, but just hiding the tooltip:
```
  .pnlm-about-msg {
    width: 0;
    height: 0;
    padding: 0;
    a { 
      display: none; 
      }
  }
```

**Comment by Marty-McFlyer** [comment]
Close, but there's some white text that still appeared with your method.
After a little fiddling I found that hiding them works best.  My new
listener is unimpeded now. Thanks!

.pnlm-about-msg {
   visibility: hidden;
    a {
        visibility: hidden;
      }
  }

**Comment by schystz** [comment]
A little late, but thanks for the tips @Marty-McFlyer & @ahoess !

Hiding it using CSS works for me as well. I am closing the issue since I am already happy with this solution.

More power @hoaiduyit ! 💪

**Comment by iReivax1** [comment]
Hi, what do i do after editing the css, like how do i "recompile". It is still showing when right clicking. Thanks

**Comment by schystz** [comment]
@iReivax1 you need to add it to your website's css, don't edit the library's css directly

**Comment by iReivax1** [comment]
Oh right. Thanks!

**Comment by zhaohuazhu** [comment]
If you use the version you build by yourself, you can re-write the "contextmenu" event for removing the tooltip with the link.
Open the "pannellum.js", and search "dragFix.addEventListener('contextmenu', aboutMessage);", replace it with:

`dragFix.addEventListener('contextmenu', function(event){
            event.preventDefault();
        });`

then save. all are done.

**Comment by zeuspsy0x1** [comment]
I created a css file and imported it on the component where I have all the configuration for the image. 

The css file looks like this 

-------------------------
  .pnlm-about-msg {
        visibility: hidden;
  }

  .pnlm-about-msg a {
        visibility: hidden;
   }
------------------------

I thought that I had to add the classname to the parent div component, but it doesn't work that way. Importing the css to the component does the job. 

I'll leave my image component just in case someone wants to see it.

-------------------------
import React from "react";
import ReactPannellum, { getConfig } from "react-pannellum";
import "./threeSixtyImage.css"

class Image extends React.Component {
  click() {
    console.log(getConfig());
  }

  render() {
    const config = {
      autoRotate: -2,
      autoLoad: true,
      showZoomCtrl: false,
      showFullscreenCtrl: false,
      mouseZoom: false,
          yaw: 0,
          pitch: 0,
          fov: 0,
          minYaw: -180,
          maxYaw: 180,
          hfov: 120
    };

    return (
      <div style={{
                    width: '90vw',  
                    height: '53vw', 
                    background: "#000000",
                    zIndex: -1,
                    marginTop: 0,
                    position: "absolute",
                    top: '0px'
                  }}>
        <ReactPannellum
          style={{ width: "100vw", height: "100%" }} 
          id="1"
          sceneId="firstScene"
          /* 
      imageSource="https://res.cloudinary.com/dnw4kirdp/image/upload/c_scale,w_6144/v1683653189/Portfolio/aaa_hfeqho.jpg" */
          imageSource='/600kbDARK.webp'
          config={config}
          autoLoad={true}
        />
      </div>
    );
  }
}
export default Image;
------------------------

**Comment by lucasbbsdk** [comment]
I would like to display a custom context menu. Is that possible?
