### ISSUE TITLE
Add support for Author and Title props

### ISSUE THREAD

**Issue by JoeDuncko** [hoaiduyit/react-pannellum#39]

**Comment by hoaiduyit** [comment]
Hi @JoeDuncko ,

This is a great idea, where do you want to show it.

Regards,

**Comment by JoeDuncko** [comment]
Pannellum has default positions to show the author and title. You should just need to pass them in. 

FYI, after evaluating your and other react bindings for pannellum, we decided to just use pannellum directly. This was mostly because of some missing functionality (like the missing author and title prop support) as well as pannellum being built in to your library instead of being a peer dependency.

Hope that helps a bit! Good luck with the project! I'd love to see better pannellum support in react soon!

**Comment by hoaiduyit** [comment]
Hi @JoeDuncko , I updated new version with these fixes, you can check
