### ISSUE TITLE
What version of pannellum is used for this project?

### ISSUE THREAD

**Issue by kppavlov** [hoaiduyit/react-pannellum#41]
Sorry if there is already a place where this information is shown but can not find it. I searched in the package.json, in the readme and in the code somewhere in /lib but with no success. Will be grateful if someone has this info and share it :) Thanks in advance!

**Comment by isaacp0310** [comment]
Hi @kppavlov i'm not a developer but it seems that this library is using
/* **Pannellum 2.4.1**, https://github.com/mpetroff/pannellum */

**Comment by hoaiduyit** [comment]
@kppavlov latest version is `2.4.1` from https://github.com/mpetroff/pannellum
