### ISSUE TITLE
Add getViewer() or provide the viewer as a ref

### ISSUE THREAD

**Issue by m-bp** [hoaiduyit/react-pannellum#46]
Currently there is no way to access the viewer instance which blocks me from taking screenshots or using event listeners.

I can provide a PR if needed but I also would like to know if there's any reason this doesn't exist in the first place.

**Comment by hoaiduyit** [comment]
Hi @m-bp `getViewer()` was existed before, but I dont know I why I removed it, for good I guess :D
I can put it back if you want.

**Comment by m-bp** [comment]
It would be great if you did
