### ISSUE TITLE
AWS image URL not working

### ISSUE THREAD

**Issue by salonee-vc** [hoaiduyit/react-pannellum#61]
Image Link - "https://realimmerse-app.s3.ap-south-1.amazonaws.com/assets/8hw0clw-360-panorama-miami.jpeg"

**Comment by hoaiduyit** [comment]
Hello @salonee-vc I just used your image to test my app, turn out, I dont have access to that image, could you please try to config your AWS app with CORS config, that would be help. Thanks.
![image](https://user-images.githubusercontent.com/25114154/150561945-1c2c8e6b-b439-4865-9b8b-5ad92a43c240.png)
![image](https://user-images.githubusercontent.com/25114154/150561967-8f045e51-c8cf-4cb2-ae1e-8793d51a89f5.png)
