### ISSUE TITLE
Can we implement VR view in react-pannellum

### ISSUE THREAD

**Issue by h4riharan** [hoaiduyit/react-pannellum#66]
Hi, We are using react-pannellum to display our panorama images, Is there any possibility to add a VR viewer inside the pannellum.
If possible that should be a great help, Or any suggestions would help us implement this feature in our existing panorama viewer that was made using react-pannellum.

I am planning to implement a button like this inside the panorama 
![image](https://user-images.githubusercontent.com/41290506/147531179-87e1806a-893d-4834-9545-344082883799.png)

Thanks for your time

**Comment by hoaiduyit** [comment]
Hi @h4riharan for VR viewer, I dont think I can support this at the moment

**Comment by h4riharan** [comment]
Its okay, 
Thanks for the response,  
If it becomes possible, It would be a great help for many like us
If there are any other suggestions, I could try to implement that.
Thank you

**Comment by hoaiduyit** [comment]
Hi @h4riharan I'll try to implement it in near future, when I have time 🛩️ . Thank for using my lib.

**Comment by h4riharan** [comment]
And I just want to thank you for this amazing library, It really helped us alot. Thanks alot🤝👍
