### ISSUE TITLE
setBounds not working

### ISSUE THREAD

**Issue by chrisAlwinYS** [hoaiduyit/react-pannellum#8]
It looks like the setHfovBounds and other restricting functions have been updated in the latest library. to remove:
`if (bounds !== []) {
        return;
      }`

As this always fails.

Any chance of updating to the latest version of Pannellum?

**Comment by hoaiduyit** [comment]
Hi @chrisAlwinYS , sorry for the lately reply.
I will check the issue and your PR to make sure it work well.
Thank for helping me.

**Comment by chrisAlwinYS** [comment]
No worries, awesome component, really saved alot of time on our end. I have had to make a forked version for this project but would rather there be one main package.

**Comment by hoaiduyit** [comment]
Hi @chrisAlwinYS ,
Your issue has been fixed. Please check it again. 
If this doesn't has any issue then close it as resolved.
Thank you.

**Comment by hoaiduyit** [comment]
Hi @chrisAlwinYS ,
As no comment in this ticket, I will close it. Any issue about this lib, please raise again.
Thanks.
