### ISSUE TITLE
How to use mouseEventsToCoords?

### ISSUE THREAD

**Issue by sharaizk** [hoaiduyit/react-pannellum#85]
Hi, I need help regarding the usage of "mouseEventsToCoords". I want to get the pitch and yaw, where I have clicked the mouse.

**Comment by masdimya** [comment]
hi @akramtouabet , have you try onMouseUp event before ? i  tried but still cannot get the event and what is "panImage" ? is it an image url ?

**Comment by akramtouabet** [comment]
Hello @masdimya ,

panImage is the image url

I got it from this : https://codesandbox.io/s/1pco8

If you dont understand anything, i'll try to answer you faster this time :)

**Comment by hoaiduyit** [comment]
Hi @masdimya so I'll mark this as done, but you can create a PR to help others people facing this issue.

**Comment by masdimya** [comment]
@hoaiduyit  here is #93
