### ISSUE TITLE
Duplicated render of .pnlm-render-container

### ISSUE THREAD

**Issue by crsp-dev** [hoaiduyit/react-pannellum#92]
Instead of 1 .pnlm-render-container being render as child of .pnlm-container its rendered 2 of it. The problem is this will create another hotspot that stick to the screen even when i move the 360. 

![image](https://user-images.githubusercontent.com/86128020/177569360-a2220dcd-37c2-42e2-ae14-b6bf43d01348.png)

**Comment by crsp-dev** [comment]
Ok i found that the problem is from the framework not from react-pannellum library. I'm using nextjs version 12, now i downgraded the version and it's works normal like it used to. Thank you very much.

**Comment by karolinakuzniewicz** [comment]
@hoaiduyit @crsp-dev did you guys maybe check how this SSR issue is related to the changes in Next v12?
